# Generated by Django 3.0.3 on 2020-04-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('song_length', models.IntegerField(verbose_name='歌曲长度 单位为ms')),
                ('genre_ids', models.CharField(max_length=10, verbose_name='歌曲流派')),
                ('artist_name', models.CharField(max_length=200, verbose_name='歌手')),
                ('composer', models.CharField(max_length=200, verbose_name='作曲')),
                ('lyricist', models.CharField(max_length=200, verbose_name='作词')),
                ('language', models.CharField(max_length=20, verbose_name='语种')),
            ],
        ),
    ]
