# Generated by Django 3.0.5 on 2020-04-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200416_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genre_subscribe',
            field=models.TextField(blank=True, verbose_name='流派订阅'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_subscribe',
            field=models.TextField(blank=True, verbose_name='语言订阅'),
        ),
    ]
