# Generated by Django 3.0.5 on 2020-04-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200416_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre_ids',
            field=models.CharField(max_length=100, verbose_name='歌曲流派'),
        ),
    ]
